---
kind: pipeline
type: docker
name: go-client-mongodb-ops-manager

platform:
  os: linux
  arch: amd64

steps:
  - name: dependencies
    image: golang:1.13
    commands:
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt-get install -y nodejs
      - npm install -g snyk
      - snyk test --org=cloud
    environment:
      SNYK_TOKEN:
        from_secret: snyk_token
    when:
      branch:
        - master
      event:
        - push

volumes:
  - name: deps
    temp: {}

trigger:
  branch:
    - master
