language: go

go:
  - 1.14.x
  - 1.15.x
  - tip

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
  include:
  - name: "Code Lint"
    before_install: make setup
    script: make lint

script: make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
